spring:
  application:
    name: vehicle-management-service
  cloud:
    config:
      uri:
      - http://localhost:8888/
  jpa:
    show-sql: true
    generate-ddl: true
  profiles:
    active:
    - dev

server:
  port: 9191
  
logging:
   level:
    root: info
 
springdoc:
  swagger-ui:
    path: /vehicle-service.html
  api-docs:
    enabled: true
    path: /vehicle-service.doc

info:
 application: 
  name: vehicle management system
  version: 1.0
 databse: mysql8.0.20
 


management: 
  endpoints:
    web:
      exposure:
        include: "*"
        

---
spring:
  #cloud:
    #config:
      #profile: dev
#  profiles: dev
  datasource:
    username: root
    password: root
#    url: jdbc:mysql://localhost:3306/vehicle-management-service
#    url: jdbc:mysql://192.168.99.100:3306/medilab-department-service
#    url: jdbc:mysql://medilab-department-mysql-container:3306/medilab-department-service
    url: jdbc:mysql://vehicle-service-mysql-container:3306/vehicle-service-mysqldb
#    url: jdbc:mysql://192.168.99.100:3306/vehicle-service-mysqldb
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
 # profiles: stage
  #cloud:
    #config:
      #profile: stage
  h2:
    console:
      enabled: true
      path: /h2Console
  